print("Getting to know you!")
print()
userName = input("What is your name?: ")
favFood = input("What is your favorite food?: ")
favMusic = input("What is your favorite music?: ")
userLocation = input("Where are you from?: ")
print()
print("You are", userName)
print("You're probably hungry for", favFood)
print("and you're definitely getting your groove on to")
print(favMusic)
print("living in the amazing", userLocation)